
name: Split repo into separate 'read-only' mods

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  split:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Configure GitHub Actions bot
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - name: Split repo
        run: |
          ./.build/init-remotes
          ./.build/split
